#! /bin/sh

# source colors from wal
# . $HOME/.cache/wal/colors.sh
. $HOME/.dotfiles/wal/color_manipulation.sh


xrandr --output "DisplayPort-1" --auto --primary --output "HDMI-A-1" --left-of "DisplayPort-1" --auto

feh --no-fehbg --bg-scale "$HOME/.dotfiles/wallpapers/knight.jpg"

xsetroot -cursor_name left_ptr

xsetwacom --set "17" MapToOutput HDMI-A-1

killall -9 picom xfce4-power-manager dunst sxhkd polybar
#pgrep -x sxhkd > /dev/null || sxhkd &

sxhkd &

dunst -config $HOME/.config/dunst/dunstrc &

xfce4-power-manager &

while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/picom/picom.conf --experimental-backends &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

glava --desktop --force-mod radial

#$HOME/.config/i3/bin/launchbar.sh
#polybar -q bspwm -c ~/.config/polybar/config &
#polybar -q status -c ~/.config/polybar/config &


bspc monitor DisplayPort-1 -d TERM WEB MAIL CODE MUSIC CHAT GAMES VAM BLENDER CID
bspc monitor HDMI-A-1 -d _TERM _WEB _MAIL _CODE _MUSIC _CHAT _GAMES _VAM _BLENDER _CID

bspc config border_width         1
bspc config window_gap         24 
bspc config top_padding  36
bspc config bottom_padding  36
bspc config normal_border_color "$color0"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color1"


bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a fm state=floating sticky=on hidden=on
alacritty --class fm,fm -e ranger &

bspc rule -a obsidian state=floating sticky=on hidden=on
obsidian &
