#! /bin/bash

# source colors from wal
# . $HOME/.cache/wal/colors.sh
#. $HOME/.dotfiles/wal/color_manipulation.sh

# some sophisticated variables to use for comfy
#

LeftMonitor="DisplayPort-1"
RightMonitor="HDMI-A-1"


# set and orient Monitors
xrandr --output $LeftMonitor --auto --primary --output $RightMonitor --right-of $LeftMonitor --auto

	# set explicitly german keyboard layout
setxkbmap de

xsetroot -cursor_name left_ptr

xsetwacom --set "17" MapToOutput $RightMonitor 



# run feh with image to set background
feh --no-fehbg --bg-scale "$HOME/.dotfiles/wallpapers/knight.jpg"


# Remove running processes for dependencies
killall -9 picom xfce4-power-manager dunst sxhkd polybar
#pgrep -x sxhkd > /dev/null || sxhkd &

# Start simply X hotkey daemon
sxhkd &

# Start dunst as notification handler
dunst -config $HOME/.config/dunst/dunstrc &

# Start Power Manager
xfce4-power-manager &

# Start and wait for picom to run
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/picom/picom.conf &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &



bspc monitor $LeftMonitor -d TERM WEB MAIL CODE MUSIC CHAT GAMES VAM BLENDER CID
bspc monitor $RightMonitor -d _TERM _WEB _MAIL _CODE _MUSIC _CHAT _GAMES _VAM _BLENDER _CID

bspc config border_width 0
bspc config border_radius 8
bspc config window_gap 24
bspc config top_padding 36
bspc config bottom_padding 32
bspc config normal_border_color "$color0"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color1"


bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspc rule -a fm state=floating sticky=on hidden=on
#alacritty --class fm,fm -e ranger &

#bspc rule -a obsidian state=floating sticky=on hidden=on
#obsidian &
#

$HOME/.config/bspwm/autostart.sh
