#!/bin/bash
export SCRIPTPATH
SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"


# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down


# Boot picom or compton if it exists
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --experimental-backends > /dev/null &


# Set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"


# Set background
feh --bg-fill "$SCRIPTPATH"/background.png

dunst &

polybar status & 
polybar main &

index=0
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width

