modkey = "Mod4"
workspaces = [
    { "id"= 0, "height"=2160, "width"=3840, "x"=1920, "y"=0 }, ## HDMI-A-0 (4k)
    { "id"= 1, "height"=1080, "width"=1920, "x"=0, "y"=0 }, ## HDMI-A-1 (xppen)
]
tags = [" TERM", " WEB", " MAIL", " CODE", " MUSIC"," CHAT"," GAMES", " VAM"," BLENDER", " CID", " VIRT"]


## Layouts
layouts = [
    #"MainAndDeck",
    "MainAndVertStack",
    #"MainAndHorizontalStack",
    #"GridHorizontal",
    #"EvenHorizontal",
    #"EvenVertical",
    #"Fibonacci",
    #"CenterMain",
    "CenterMainBalanced",
    #"RightWiderLeftStack",
    #"LeftWiderRightStack",
    "Monocle",
]
layout_mode = "Tag"

## Window Focus
focus_behaviour = "Sloppy" # Can be Sloppy, ClickTo, or Driven
focus_new_windows = true


scratchpad = [
    { name = "Filemanager", value="alacritty -e ranger", x=960, y=540, width=1920, height=1080 },
    { name = "Todoist", value="todoist", x=960, y=540, width=1920, height=1080 },
    { name = "Joplin", value="joplin-desktop", x=960, y=540, width=1920, height=1080 },
]

## Keybinds
keybind = [

  ## Format
  # { command = "", value = "", modifier = [], key = "" }

  { command = "CloseWindow", modifier = ["modkey"], key = "c" },

  ## Reload/Quit LeftWM
  { command = "SoftReload", modifier = ["Control", "Shift"], key = "r" },
  { command = "Execute", value = "pkill -KILL -u $USER", modifier = ["Control", "Shift"], key = "q" },

  { command = "IncreaseMainWidth", value = "5", modifier = ["modkey"], key = "l" },
  { command = "DecreaseMainWidth", value = "5", modifier = ["modkey"], key = "h" },

  { command = "FloatingToTile", modifier = ["modkey","Shift"], key = "t" },
  { command = "ToggleFullScreen", modifier = ["modkey"], key = "f" },

  { command = "MoveWindowUp", modifier = ["modkey", "Shift"], key = "Right" },
  { command = "MoveWindowDown", modifier = ["modkey", "Shift"], key = "Left" },

  { command = "FocusWindowUp", modifier = ["modkey"], key = "Right" },
  { command = "FocusWindowDown", modifier = ["modkey"], key = "Left" },
  
  { command = "SwapTags", modifier = ["modkey"], key = "w" },
  { command = "ToggleScratchPad", value="Todoist", modifier = ["modkey"], key = "t" },
  { command = "ToggleScratchPad", value="Joplin", modifier = ["modkey"], key = "n" },
  { command = "ToggleScratchPad", value="Filemanager", modifier = ["modkey"], key = "e" },

  ## Switch Layouts
  { command = "NextLayout", modifier = ["modkey", "Control"], key = "Right" },
  { command = "PreviousLayout", modifier = ["modkey", "Control"], key = "Left" },

  ## Switch From Tag 1 to 7
  { command = "GotoTag", value = "1", modifier = ["modkey"], key = "1" },
  { command = "GotoTag", value = "2", modifier = ["modkey"], key = "2" },
  { command = "GotoTag", value = "3", modifier = ["modkey"], key = "3" },
  { command = "GotoTag", value = "4", modifier = ["modkey"], key = "4" },
  { command = "GotoTag", value = "5", modifier = ["modkey"], key = "5" },
  { command = "GotoTag", value = "6", modifier = ["modkey"], key = "6" },
  { command = "GotoTag", value = "7", modifier = ["modkey"], key = "7" },
  { command = "GotoTag", value = "8", modifier = ["modkey"], key = "8" },
  { command = "GotoTag", value = "9", modifier = ["modkey"], key = "9" },
  { command = "GotoTag", value = "10", modifier = ["modkey"], key = "0" },
  { command = "GotoTag", value = "11", modifier = ["modkey","Alt"], key = "1" },

  ## Move Windows From One Tag to Another
  { command = "MoveToTag", value = "1", modifier = ["modkey", "Shift"], key = "1" },
  { command = "MoveToTag", value = "2", modifier = ["modkey", "Shift"], key = "2" },
  { command = "MoveToTag", value = "3", modifier = ["modkey", "Shift"], key = "3" },
  { command = "MoveToTag", value = "4", modifier = ["modkey", "Shift"], key = "4" },
  { command = "MoveToTag", value = "5", modifier = ["modkey", "Shift"], key = "5" },
  { command = "MoveToTag", value = "6", modifier = ["modkey", "Shift"], key = "6" },
  { command = "MoveToTag", value = "7", modifier = ["modkey", "Shift"], key = "7" },
  { command = "MoveToTag", value = "8", modifier = ["modkey", "Shift"], key = "8" },
  { command = "MoveToTag", value = "9", modifier = ["modkey", "Shift"], key = "9" },
  { command = "MoveToTag", value = "10", modifier = ["modkey", "Shift"], key = "0" },
  { command = "MoveToTag", value = "11", modifier = ["modkey","Alt", "Shift"], key = "1" },
]

